task:
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true' && $CIRRUS_PR == ''
  container:
    dockerfile: .ci/Dockerfile
    cpu: 4
    memory: 8G
  upgrade_script:
    - flutter channel master
    - flutter upgrade
    - git fetch origin master
  activate_script: pub global activate flutter_plugin_tools
  matrix:
    - name: analyze
      # TODO(goderbauer): remove custom-analysis once gauge has proper API docs.
      script: ./script/incremental_build.sh analyze --custom-analysis gauge
    - name: publishable
      script: ./script/check_publish.sh
      depends_on:
        - analyze
    - name: test+format
      format_script: ./script/incremental_build.sh format --travis --clang-format=clang-format-5.0
      test_script: ./script/incremental_build.sh test
      depends_on:
        - analyze
    - name: build-apks+java-test
      env:
        matrix:
          BUILD_SHARDING: "--shardIndex 0 --shardCount 2"
          BUILD_SHARDING: "--shardIndex 1 --shardCount 2"
      script:
        - ./script/incremental_build.sh build-examples --apk
        - ./script/incremental_build.sh java-test  # must come after apk build
      depends_on:
        - analyze

task:
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true'
  name: build-ipas
  osx_instance:
    image: high-sierra-xcode-9.4.1
  env:
    PATH: $PATH:/usr/local/bin
    matrix:
      BUILD_SHARDING: "--shardIndex 0 --shardCount 2"
      BUILD_SHARDING: "--shardIndex 1 --shardCount 2"
  setup_script:
    - pod repo update
    - git clone https://github.com/flutter/flutter.git
    - git fetch origin master
    - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
    - flutter doctor
    - pub global activate flutter_plugin_tools
  build_script:
    - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
    - ./script/incremental_build.sh build-examples --ipa
